apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernates-client-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: bkci-kube-client-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
