#environment Deployment
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-environment
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: environment
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: environment
  replicas: {{ .Values.environment.replicas }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: environment
        {{- if .Values.environment.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.environment.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.common.serviceAccount }}
      {{- if .Values.environment.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.environment.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.environment.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.environment.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.environment.podAffinityPreset "component" "environment" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.environment.podAntiAffinityPreset "component" "environment" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.environment.nodeAffinityPreset.type "key" .Values.environment.nodeAffinityPreset.key "values" .Values.environment.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.environment.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.environment.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.environment.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.environment.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.environment.priorityClassName }}
      priorityClassName: {{ .Values.environment.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.environment.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.environment.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}        
      containers:
        - name: environment
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          {{- if .Values.environment.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.environment.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.environment.resources }}
          resources: {{- toYaml .Values.environment.resources | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.environment.resources.requests.cpu | quote }}
              memory: {{ .Values.environment.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.environment.resources.limits.cpu | quote }}
              memory: {{ .Values.environment.resources.limits.memory | quote }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MS_NAME
              value: environment
            - name: JVM_XMS
              value: {{ .Values.environment.env.JVM_XMS }}
            - name: JVM_XMX
              value: {{ .Values.environment.env.JVM_XMX }}
          workingDir: /data/workspace/environment
          command:
            - "/bin/bash"
            - "-c"
            - |
              cp /data/workspace/backend.bkci.sh .;
              /bin/bash backend.bkci.sh;
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: http
            initialDelaySeconds: 300
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.config.bkCiDataDir }}
      volumes:
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "common.names.fullname" . }}-storage{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
